Oop
SiarheiBalt/Team pull request #3
Opened 2021-10-01 12:04 UTC by SiarheiBalt

2021-10-05 08:32 UTC, Aliaksandrlosich requested changes

2021-10-05 08:32 UTC, Aliaksandrlosich commented on Task3/src/app.js
> +  if (event.target.id === 'invite') bestSound.inviteCustomer(getClient());
Вместо заборчика ифов, можно использовать обьект.

2021-10-05 08:32 UTC, Aliaksandrlosich commented on Task3/src/app.js
> +  array.forEach((element) => {
Через append можно сразу вставлять в dom одной кипой, без форыча

2021-10-05 08:32 UTC, Aliaksandrlosich commented on Task3/src/index.html
> +          Выбрать клиента №
Не забывай теги для текста

2021-10-05 08:32 UTC, Aliaksandrlosich commented on Task3/src/modules/equipment/amp.js
> +export const amp = new Amp("black", "Marshall", 1995, "Усилитель");
А если я захочу другую модель? или не сколько. Экспортируй только сам класс, без инициализации. Где он тебе нужен, там и проинициализируешь. Плюс у тебя класс "Усилитель",  поле со значением "Усилитель" должно быть задано в самом конструкторе, а не передвать параметры.  Иначе я беру класс Amp но передам ему "барабаны"

2021-10-05 08:32 UTC, Aliaksandrlosich commented on Task3/src/modules/equipment/computer.js
> +export const computer = new Computer("white", "Integrall", 2019, "Компьютер");
Аналогично замечанию с усилителем

2021-10-05 08:32 UTC, Aliaksandrlosich commented on Task3/src/modules/equipment/drum.js
> +export const drums = new Drums("White", 2013, "China", 30, "барабаны", 5);
То что это барабаны, должно быть сразу задано в классе. А не тут. Аналогично с усилителем

2021-10-05 08:32 UTC, Aliaksandrlosich commented on Task3/src/modules/equipment/guitar.js
> +export const guitar = new Guitar("black", 2000, "Japan", 15, "гитара", 6);
Аналогично с усилителем

2021-10-05 08:32 UTC, Aliaksandrlosich commented on Task3/src/modules/equipment/musicalInstrument.js
> +      `Инструмент ${this.name} зарезервирован клиентом ${this.customer}`;
Что это за запись?

2021-10-05 08:32 UTC, Aliaksandrlosich commented on Task3/src/modules/equipment/recordingEquip.js
> +    this.isOn = false;
Лучше всегда значения возвращать через методы, чем на прямую. Это облегчит контроль над переменной, если возвращать значение через метод, её нельзя будет случайно изменить

2021-10-05 08:32 UTC, Aliaksandrlosich commented on Task3/src/modules/person/administrator.js
> +class Administrator extends StudioWorker {
Почему в методах которые бронируют, только текст, а сама бронь нигде не делается?

2021-10-05 08:32 UTC, Aliaksandrlosich commented on Task3/src/modules/studio.js
> +        this.employees.engineer.work();
Это всё можно было спрятать в методе инженера. Он ведь всё настраивает.

2021-10-05 08:32 UTC, Aliaksandrlosich commented on Task3/src/modules/studio.js
> +import { guitar } from "./equipment/guitar.js";
Если ты экспортируешь только одно значение из файла, используй export default, что бы при импорте быть без деструктуризации

2021-10-05 08:32 UTC, Aliaksandrlosich commented on Task3/src/modules/studio.js
> +      if (customer.getFullName() !== client) acc.push(client);
Магическое сравнение

2021-10-05 12:39 UTC, SiarheiBalt commented on Task3/src/modules/studio.js
> +      if (customer.getFullName() !== client) acc.push(client);
Сравнение по имени и фамилии. Ранее в массив customers записываю посетителей по имени и фамилии, так же их и удаляю. Переделал на filter.

2021-10-05 12:51 UTC, SiarheiBalt commented on Task3/src/modules/person/administrator.js
> +class Administrator extends StudioWorker {
Бронь происходит в классе Room, метод reserveRoom. В свойство customer класса Room записывается посетитель.
Так же и в MusicalInstrument, метод reserveInstruments.

2021-10-05 13:43 UTC, SiarheiBalt commented on Task3/src/modules/person/administrator.js
> +class Administrator extends StudioWorker {
Перенес бронь комнаты в метод администратора

2021-10-07 07:24 UTC, Aliaksandrlosich commented on Task3/src/modules/person/customer.js
> +    if (this.cash - cost < 0) {
Магическое сравнение

2021-10-07 11:16 UTC, SiarheiBalt commented on Task3/src/modules/person/customer.js
> +    if (this.cash - cost < 0) {
Исправил. Создал переменную.

2021-10-07 12:05 UTC, Aliaksandrlosich approved these changes

2021-10-07 12:06 UTC, merged